### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#16]
Make UI responsive with special consideration for mobile views.

**Comment by searls** [comment]
Any comment on the priority of this one? I [hacked up](https://gist.github.com/searls/7fd2c3223571a58a81006e7da66bd064) the netlify CMS well enough to kinda sorta use it from an iPhone, but of course that's not much of a solution

I think I might be an outlier, but personally being able to quickly post and edit a blog from my phone is really the only use case for a static CMS, since I'd otherwise just be on a computer and using an editor. Was disappointed when [TinaCMS](https://tina.io) launched (a successor to [Forestry](https://forestry.io) and still was completely unusable from a phone

**Comment by denyskon** [comment]
> Any comment on the priority of this one? I [hacked up](https://gist.github.com/searls/7fd2c3223571a58a81006e7da66bd064) the netlify CMS well enough to kinda sorta use it from an iPhone, but of course that's not much of a solution
> 
> I think I might be an outlier, but personally being able to quickly post and edit a blog from my phone is really the only use case for a static CMS, since I'd otherwise just be on a computer and using an editor. Was disappointed when [TinaCMS](https://tina.io) launched (a successor to [Forestry](https://forestry.io) and still was completely unusable from a phone

I'm working on it currently:
![Screenshot_20230429-222324~2.png](https://user-images.githubusercontent.com/47871822/235358047-4160d55b-9887-45d7-8db1-844752457c28.png)

I don't know how much it'll take to have something I can open a PR for, but it's definitely a big a priority for me too :)

**Comment by searls** [comment]
Woot! Looks awesome!

I am pretty sure you'll be the only static CMS that supports mobile in any form.

**Comment by KaneFreeman** [comment]
Mobile support will be available in `v3.0.0`, coming to beta soon.

**Comment by denyskon** [comment]
@KaneFreeman Isn't this resolved now?
