### ISSUE TITLE
Add Pagination to Published Posts Page

### ISSUE THREAD

**Issue by clarnx** [StaticJsCMS/static-cms#36]
Rather than show ALL posts in the posts page forever and ever, there should be a way to navigate to more pages when your posts are many. It would also be appropriate to have a "show more" button at the bottom and incrementally add more posts to the end of the page.

**Comment by KaneFreeman** [comment]
This is partially the behavior at current. When nothing is sorted, filtered or grouped the current behavior is to load incrementally when scrolling. However when sorting, filtering or grouping that occurs in the UI and thus requires all entries be loaded into memory. UI pagination could still be added in that case though to help with UI performance.

**Comment by KaneFreeman** [comment]
Unfortunately, we have to load all of the data to be able to sort. The data from the git providers comes unsorted, thus it must all be loaded in order to do any kind of meaningful sort. That is why the default behavior is not to sort.

This feature is simply to provide UI paging, which may help with performance on a very large data set. However, all the data still must be loaded from the backend in order to perform the sort. So any pagination we add is applied after data loading.
