### ISSUE TITLE
Performance issue with media-heavy project

### ISSUE THREAD

**Issue by timotheegoguely** [StaticJsCMS/static-cms#780]
Hi,

I'm working on a Hugo project with a lot of media (~2000 files, mostly images and some PDFs) stored in `/static/media` and I'm using GitLab as a git provider and Static CMS `v2.2.0`.

When I want to display a single post from a big posts collection (~500 items), why does the app need to fetch all the repo images before being able to display the editor UI? Wouldn't there be a way to avoid all these requests and improve app performance?

<img width="834" alt="image" src="https://user-images.githubusercontent.com/8271134/236685749-a2d65f4c-63fd-4149-9685-3dcdc1604cf3.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8271134/236686985-d32378e0-8086-434c-af06-165221a470d6.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/8271134/236685882-6e613d5a-c0a9-4115-abcf-8f989be8a5e8.png">

As it is, it becomes almost impossible for content editors to use Static CMS to update their website content because of the slowness of the app (each page sometimes takes more than 1 minute to load).

**Comment by denyskon** [comment]
I think it is for the grid view, as there a preview of the head image is provided. You should be able to avoid it buy using a custom preview card template which doesn't involve previewing images (https://www.staticcms.de/docs/custom-previews#collection-card-preview)

**Comment by KaneFreeman** [comment]
Yeah this behavior is not desirable. It ideally would:

1. Wait to load only the first few image when you actually open up the media library
2. Load in the other images as necessary.

**Comment by timotheegoguely** [comment]
Is it something that can be improved easily or does it need a lot of rework?

**Comment by KaneFreeman** [comment]
Actually I'm double checking, that is what the media library is suppose to be doing already. So I need some more information to look into this further:

1. Are you storing your images at the root `media_folder` or are they in a collection specific folder?
2. Which page are you loading when you see all the requests? The main collection view or the editor itself?

**Comment by timotheegoguely** [comment]
1. All media (images and files) are stored at the root `media_folder`
2. The massive requests occurs when I'm clicking on any page from any collection (not the main collection view but the editor itself).

**Comment by denyskon** [comment]
> Actually I'm double checking, that is what the media library is suppose to be doing already. So I need some more information to look into this further:
> 
> 1. Are you storing your images at the root `media_folder` or are they in a collection specific folder?
> 2. Which page are you loading when you see all the requests? The main collection view or the editor itself?

At some point, media is loaded and saved in the entry state (mediaPaths entry property / state.mediaLibrary) which I already noticed when implementing folder support. I didn't manage to find out when that happens though

**Comment by KaneFreeman** [comment]
A list of them is loaded into the entry but its only the meta data. The actual file is not loaded until its needed for display.

I've been trying without success to replicate this. I have tested this using both Gitlab and Github backends. I've uploaded hundreds of images to them and the only ones I see load on editor load are the ones selected in image or file widgets. The rest do no load till the media library modal is opened, even then they are only loaded when you scroll to them.


I have a hunch where this might be occurring. But I need you to help me confirm a couple of things.

1. If you go into the editor, let it finish loading, then reload the page. Does it request all of the image files?
2. If you open up Static CMS and let it sit on the collection page. Does it request a bunch of image files?

**Comment by KaneFreeman** [comment]
After a lot of testing, I was able to narrow down some issues that are causing these images to load. As it is today, the card/grid view in the collections page tries to load the image for the first image field it finds. It then displays that image when you view the card/grid view.

However, it was doing a couple of things that are the likely culprits of your performance issues:

1. It would load these images even when you had not switched to the card/grid view (so they were always loaded)
2. It would load images for EVERY entry in a collection

So if you had 500 entries each with a unique image, then 500 images were loaded every time you went to that collection.

The next release has some changes that will drastically help reduce this:

1. Images are no longer loaded if you are on the table view (so if you never switch to the card/grid view, then no images will be loaded at all)
2. Both the table view and card/grid view are virtualized. This means only the rows (for table view) or cards (for card/grid view) that are currently on screen (or just above/below your scroll position) will actually be rendered. Thus images for the card/grid view will only be loaded when you switch to that view and actually scroll to a given entry.

Since the table view is the default, this means:
- 0 images will be loaded on initially going to a collection
- If you switch to the card/grid view and the initial load, which will vary based on the size of your monitor, should be around or less than 20 images regardless of the total entry count.


This fix also completes #36

**Comment by timotheegoguely** [comment]
Fantastic! Looking forward to testing the next version!
