### ISSUE TITLE
Re-introduce Editorial Workflow

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#896]
This workflow involves changes being commited to their own branches with pull/merge requests being opened back to the main branch. The pull/merge request will be merged when the changes are `published`.

**Comment by denyskon** [comment]
I tried to implement editorial workflow for Gitea in https://github.com/decaporg/decap-cms/pull/6808, which failed because Gitea lacks some APIs which were required for editorial workflow in Decap.
What are your plans for backend support for editorial workflow? Will it only be available for the GitHub backend, or would you like it being available for every backend? If so, we may need additional changes to the Gitea API before it would be possible

**Comment by KaneFreeman** [comment]
I actually have it working on every backend but Gitea at the moment. I have not gotten around to looking into their API yet.

**Comment by denyskon** [comment]
Sounds great! If you notice that anything is missing for Gitea, ping me - I've contributed a lot to Gitea during the last month and might be able to make the required changes :)

**Comment by almereyda** [comment]
Now that #898 has been merged and shipped with https://github.com/StaticJsCMS/static-cms/releases/tag/v4.0.0-beta.0, can this be closed?

**Comment by KaneFreeman** [comment]
The Gitea backend is coming out of beta with `v4.0.0` so before it ships I will be adding support for it in the editorial workflow. For now this issue is remaining open to keep track of that.

**Comment by KaneFreeman** [comment]
I decided to move forward with the `v4.0.0` release with out support for Gitea. I have opened #1047 to track progress on updating the Gitea backend.
