### ISSUE TITLE
Preview is blank after inserting a table

### ISSUE THREAD

**Issue by torce** [StaticJsCMS/static-cms#994]
The preview frame shows an empty markdown preview after inserting a table.

[Screencast.webm](https://github.com/StaticJsCMS/static-cms/assets/3646997/ae7f63cd-ef12-4290-97b8-578b2299946e)

**Comment by arctixdev** [comment]
This seems to be the underlying problem: https://github.com/remarkjs/remark-gfm/issues/57#issuecomment-1723719893

**Comment by arctixdev** [comment]
Downgrading remark-gfm to 3.0.1 fixes the problem. It is because the entire markdown "ecosystem" apperently changes a lot of stuff and is rolling out new major versions with breaking changes as said here https://github.com/remarkjs/remark-gfm/issues/57#issuecomment-1733741518 

The version currently used of remark-gfm (4.0.0) has thoose big changes and therefore breaks. 

I have created a pr that downgrades remark-gfm and fixes the issue: #1012

**Comment by KaneFreeman** [comment]
I going to opt for upgrading all of the dependencies instead of downgrading. It will have to be done eventually anyways to maintain support. I am closing this PR in favor of #1013

**Comment by KaneFreeman** [comment]
Thanks for finding this. I going to opt for upgrading all of the dependencies instead of downgrading. It will have to be done eventually anyways to maintain support. I have opened a PR to address this #1013
