### ISSUE TITLE
[v4 beta] media path returned instead of public path

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#996]
I use the following configuration:
```js
  media_folder: "/static/media",
  public_folder: "/media",
```
which resulted in files being saved as `/static/media/blog/image.webp` but the image widget returning `/media/blog/image.webp`. Now, the image widget returns `static/media/blog/image.webp`.

**Comment by denyskon** [comment]
Thanks a lot!

**Comment by nuuw-studio** [comment]
Using `v4.3.0` it looks like this issue is still present when using `media_library: folder_support: true` 

Using the following config:
```
media_library:
  folder_support: true
media_folder: "/assets/images"
public_folder: "/images"
```
Results in the following paths in my frontmatter: `image: assets/images/...`

Is it possible that the folder_support didn't receive the fix? Or am I doing something wrong?
